name: tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libcrypto dependency
        run: sudo apt-get update && sudo apt-get install -y libssl1.1
      - run: cd auth && npm install && npm run test:ci
